---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MoMo.
--- DateTime: 2018/11/7 16:13
---

backBtn = Label()
backBtn:text("< 返回"):marginTop(window:statusBarHeight() + 10):marginLeft(16)
backBtn:onClick(function()
Navigator:closeSelf(0)
end)
window:addView(backBtn)

heights = {170,140,120,170,170,155,120}

measureViews = {measureView = View(), m_contentText = Label(), m_positionLabel = Label()}

local screenSize = System:screenSize()
local screen_w = screenSize:width()
local screen_h = screenSize:height()
print(screenSize)

http = Http()
dataSource = Map()

momentListView = TableView(true, true)
momentListView:width(screen_w):height(screen_h -64):marginTop(64)

momentListView:setRefreshingCallback(function()
    fetchData()
end)
momentListView:setLoadingCallback(function()
http:post("https://mln.com/momentlist", nil, function(success, rspInfo, error)
if success then
print("setLoadingCallback")
print(rspInfo)
allcount = dataSource:size()
addCount = rspInfo:get("list"):size()
dataSource:addAll(rspInfo:get("list"))
momentListView:stopLoading()
momentListView:insertCellsAtSection(1, allcount + 1, allcount+ addCount)
end
end)
end)

kMomentCellReuseId = "moment"
momentListAdapter = TableViewAutoFitAdapter()
momentListAdapter:rowCount(function()
    print("rowCount", dataSource:size())
    return dataSource:size()
end)
momentListAdapter:initCell(function(cell)
    print("initCell")
    local mommentCell = require("momentCell")
    cell.mommentCell = mommentCell:new()
    cell.mommentCell:setupUI(cell.contentView)
end)
momentListAdapter:fillCellData(function(cell, section, row)
    print("fillCellData")
    cell.mommentCell:updateByItem(dataSource:get(row),row)
end)

momentListView:adapter(momentListAdapter)

window:addView(momentListView)

function fetchData()
http:post("https://mln.com/momentlist", nil, function(success, rspInfo, error)
if success then
print(rspInfo)
dataSource = rspInfo:get("list")
print("fetchData")
momentListView:stopRefreshing()
momentListView:reloadData()
end
end)
end
fetchData()
