---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhang.ke.
--- DateTime: 2018/11/22 上午11:29
---

local _class = {}
_class._version = '1.0'
_class._classname = ''

function _class:createCommonTabLinearLayout(contentView, bgColor)
    local btnScrollView = ScrollView(true)

    btnScrollView:height(50)
    btnScrollView:width(screen_w)

    if bgColor then
        btnScrollView:bgColor(bgColor)
    end

    contentView:addView(btnScrollView)

    local btnsContainer = LinearLayout(LinearType.HORIZONTAL):height(50):setWrapContent(true)
    btnScrollView:addView(btnsContainer)

    return btnsContainer
end

function _class:addTabFromData(dataSource, tabsContainer)

    local tabs = {}
    for i, v in ipairs(dataSource) do
        local start, last = string.find(v, "demo.")
        local name
        if last and last < #v then
            name = string.sub(v, last + 1, #v)
        else
            name = v
        end
        local tab = Label():setAutoFit(true):textAlign(TextAlign.CENTER):setMinWidth(80):marginLeft(5):padding(0, 5, 5, 5):height(50):fontSize(14):text(name):bgColor(Color(211, 211, 211, 1)):textColor(Color(0, 0, 0, 1))
        tabsContainer:addView(tab)
        tabs[v] = tab
    end

    return tabs
end

function _class:initShowLabel(showLabel, width, height)
    showLabel:width(width - 16):height(height - (16 + (40 + 5) * 3) - 8):lines(0):fontSize(20):textAlign(TextAlign.LEFT):textColor(Color(0, 0, 0, 1)):bgColor(Color(222, 222, 222, 1)):y(16 + (40 + 5) * 3):x(8):textColor(Color(0, 0, 0, 1))
    return showLabel
end

return _class