---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-08-23-08-2019 20:01
---

--- 暂时设置为全局，避免被gc
 MeiLiShuoMainView = require("MMLuaKitGallery.TabContainerView")
 MeiLiShuoMainView:setup()







