// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBDeviceCommand.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "PbdeviceCommand.pbobjc.h"
#import "PbbaseCommand.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PbdeviceCommandRoot

@implementation PbdeviceCommandRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - PbdeviceCommandRoot_FileDescriptor

static GPBFileDescriptor *PbdeviceCommandRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - pbdevicecommand

@implementation pbdevicecommand

@dynamic hasBasecommand, basecommand;
@dynamic name;
@dynamic model;

typedef struct pbdevicecommand__storage_ {
  uint32_t _has_storage_[1];
  pbbasecommand *basecommand;
  NSString *name;
  NSString *model;
} pbdevicecommand__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "basecommand",
        .dataTypeSpecific.className = GPBStringifySymbol(pbbasecommand),
        .number = pbdevicecommand_FieldNumber_Basecommand,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(pbdevicecommand__storage_, basecommand),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = pbdevicecommand_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(pbdevicecommand__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "model",
        .dataTypeSpecific.className = NULL,
        .number = pbdevicecommand_FieldNumber_Model,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(pbdevicecommand__storage_, model),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[pbdevicecommand class]
                                     rootClass:[PbdeviceCommandRoot class]
                                          file:PbdeviceCommandRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(pbdevicecommand__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
