---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XiongFangyu.
--- DateTime: 2019-07-01 18:44
---

local clz = luajava.bindClass('org.luaj.vm2.jse.JavaClassTest')
--local print_table = require("print_table")
--print_table.print_r(getmetatable(clz))
--print_table.print_r(getmetatable(getmetatable(clz)))

print(clz:getInt(), clz.A_STATIC_INT)
clz:doSomeThing('lua string')

local obj = luajava.new(clz)
print('init : ', obj:aInt(), obj:aFloat())
obj['aInt'] = 3
obj['aFloat'] = 4.2

print('after : ', obj:aInt(), obj:aFloat())