// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBDetailReportCommand.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class pbbasecommand;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PbdetailReportCommandRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PbdetailReportCommandRoot : GPBRootObject
@end

#pragma mark - pbcoveragedetailcommand

typedef GPB_ENUM(pbcoveragedetailcommand_FieldNumber) {
  pbcoveragedetailcommand_FieldNumber_Basecommand = 1,
  pbcoveragedetailcommand_FieldNumber_FilePath = 2,
  pbcoveragedetailcommand_FieldNumber_RelativeFilePath = 3,
  pbcoveragedetailcommand_FieldNumber_FileData = 4,
};

@interface pbcoveragedetailcommand : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) pbbasecommand *basecommand;
/** Test to see if @c basecommand has been set. */
@property(nonatomic, readwrite) BOOL hasBasecommand;

@property(nonatomic, readwrite, copy, null_resettable) NSString *filePath;

@property(nonatomic, readwrite, copy, null_resettable) NSString *relativeFilePath;

@property(nonatomic, readwrite, copy, null_resettable) NSData *fileData;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
