---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XiongFangyu.
--- DateTime: 2019-06-03 16:26
---
local r = require('print_table')
local child2 = NonlazyChild()
--r.print_r(getmetatable(child2))

local ud = UDTest()
SBTest2:a(ud)
SBTest2:des()
SBTest2:b(ud)
SBTest2:des()

r.print_r(___Global_Native_Value[7])