---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2019-03-08 12:19
---
local _class = {}
_class._version = '1.0'
_class._classname = 'NearByPlayMoreActionView'

screenWidth= window:width()
screenHeight =  window:height()

MoreActionViewHeight = 132

containerFrameAnimation = nil

function _class:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    -- 初始化
    --self:initView()
    return o
end

function _class:show(callBack)
    self.dialog = Dialog()

    self.baseView = View()
            :width(screenWidth)
            :height(screenHeight)

    self.bottomView = View()
    self.bottomView:width(screenWidth)
    self.bottomView:height(MoreActionViewHeight)
    self.bottomView:bgColor(Color(255,255,255,1))
    self.bottomView:cornerRadius(7)
     -- self.bottomView:y(screenHeight )



    self.baseView:addView(self.bottomView)
    self:setupContentView()

    self.dialog:setContent(self.baseView)


    self.dialog:show()

    self:showBottomView()

    self.baseView:onClick(function ()
        self:dismissBottomView()
    end)
    self.callBack = callBack






end

function _class:dismissBottomView()
    local disAnimation = FrameAnimation()
    disAnimation:setTranslateYTo(screenHeight)
    disAnimation:setDuration(0.25)
    disAnimation:start(self.bottomView)
    disAnimation:setEndCallback(function(isFinished)
        self.dialog:dismiss()
    end)
end

function _class:initShowAnimation()
    if containerFrameAnimation == nil then
        containerFrameAnimation = FrameAnimation()
    end
end


function _class:showBottomView()

    _class:initShowAnimation()

    -- containerFrameAnimation:setTranslateYTo(screenHeight- MoreActionViewHeight)

    containerFrameAnimation:setTranslateY(screenHeight, screenHeight - MoreActionViewHeight)

    containerFrameAnimation:setDuration(0.25)
    containerFrameAnimation:start(self.bottomView)
end

function _class:setupContentView()
    --先加一个不感兴趣按钮 后面扩展在做修改
    local notInteresteView = View()
            :width(60)
            :height(82)
            :marginTop(15)

    notInteresteView:onClick(function ()
        self:dismissBottomView()
        if self.callBack then
            self.callBack()
        end
    end)

    self.bottomView:addView(notInteresteView)

    local imageView = ImageView()
            :width(40)
            :height(40)
            :setGravity(Gravity.CENTER_HORIZONTAL)
            :contentMode(ContentMode.CENTER)
    notInteresteView:addView(imageView)
    imageView:image("https://s.momocdn.com/w/u/others/2018/08/29/1535526989910-share_no_interesting@2x.png")

    local label = Label()
            :width(60)
            :height(22)
            :marginTop(50)
            :setGravity(Gravity.CENTER_HORIZONTAL)
            :textAlign(TextAlign.CENTER)
            :fontSize(11)
            :text("不感兴趣")
    notInteresteView:addView(label)

end

_class:show()
return _class