---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by David.
--- DateTime: 2018/5/14 下午12:25
---



datasouce = {
    headIconName = "http://img.momocdn.com/album/4F/CF/4FCFA0D2-95E8-3C09-3760-142E6916CA1B20170701_S.jpg",
    summary = "安全等级：高",
    sections = {
        {
            sectionTitle = "通过以下设置可以提高安全等级",
            items = {
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "密码修改——1——100",
                    subtitle = nil,
                    height=400,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "密码修改——1——100",
                    subtitle = nil,
                    height=100,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "手机绑定——2——300",
                    subtitle = "已绑定",
                    height=300,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "证件信息——3——100",
                    subtitle = "未绑定",
                    height=100,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "登录保护--4--100",
                    subtitle = "已开启",
                    height=100,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "账号注销--5--200",
                    subtitle = "",
                    height=200,
                },
            }
        },

    }
}


local size = window:size()
screen_w = size:width()
screen_h = size:height()

local collectionView = CollectionView(true, true)



local adapter = CollectionViewAdapter()

adapter:initCell(function (cell)
    local normalCell = require("cells.MomentNormalCell")
    normalCell:onCreate(cell,nil)
end)

adapter:fillCellData(function (cell,section,row)
    local normalCell = require("cells.MomentNormalCell")
    local section = datasouce.sections[section]
    local items = section.items;
    local detailItem = items[row]
    normalCell:onLayout(cell,detailItem)
end)

adapter:sectionCount(function ()
    return #datasouce.sections
end)


-- 总共有多少个 子视图 item
adapter:rowCount(function (section)
    local sections = datasouce.sections;
    --找到对应的组
    return #sections[section].items
end)


adapter:selectedRow(function (cell,section,row)
    print('onclick', section,row)
end)


oneWidth = screen_w/4 - 10
oneHeight = screen_h/4



adapter:sizeForCell(function (section,row)
    local section = datasouce.sections[section]
    local items = section.items;
    local c = items[row].height / 100
    local w = 0
    if c == 4 then
        w = screen_w - 10
    else
        w = c * oneWidth
    end

--[[    if row ==3 then
        w = w+ 100
    end]]
    return Size(w, oneHeight)
end)




local layout = CollectionViewLayout()
layout:lineSpacing(10)
layout:itemSpacing(5)
layout:itemSize(Size(oneWidth, oneHeight))



collectionView:scrollDirection(ScrollDirection.HORIZONTAL)
collectionView:layout(layout)

collectionView:adapter(adapter)


collectionView:setRefreshingCallback(function ()
    print('开始刷新')
    TimeManager:setTimeOut(function ()
        print("timer 完成")
        collectionView:stopRefreshing()
        collectionView:resetLoading()
    end, 1)
end)

collectionView:setLoadingCallback(function ()
    print('开始加载')
    TimeManager:setTimeOut(function ()
        print("timer 完成")
        collectionView:stopLoading()
        collectionView:noMoreData()
    end, 1)
end)
collectionView:setScrollingCallback(function ()
    --print('滚动中')
end)
collectionView:setScrollBeginCallback(function ()
    --print('开始滚动')
end)
collectionView:setScrollEndCallback(function ()
    --print('滚动结束')
end)
print("size ", screen_w, screen_h)
collectionView:frame(Rect(0,0,screen_w,screen_h))
window:addView(collectionView)
collectionView:showScrollIndicator(true)
--collectionView:reload()
--local timer = Timer(function ()
--    print("timer 完成")
--    collectionView:startRefreshing()
--end )
--timer:delay(1)
--timer:start()