---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/9/28 下午5:45
---

content = Label()
content:width(window:width())
content:height(40)
content:text('net status:' .. NetworkReachability.networkState())
window:addView(content)

local openBtn = Label()
openBtn:text('open')
openBtn:width(40)
openBtn:height(40)
openBtn:y(50)
openBtn:bgColor(Color():hex(0xff00ff):alpha(1))
openBtn:onClick(function()
    content:text('open')
    NetworkReachability.open()
end)
window:addView(openBtn)

local closeBtn = Label()
closeBtn:width(40)
closeBtn:text('close')
closeBtn:height(40)
closeBtn:y(100)
closeBtn:bgColor(Color():hex(0xff00ff):alpha(1))
closeBtn:onClick(function()
    content:text('close')
    NetworkReachability.close()
end)

NetworkReachability.setOnNetworkStateChange(function(state)
    local stateState;
    if (state == 0)
    then
        stateState = 'NO_NETWORK'
    elseif state == 1 then
        stateState = 'CELLULAR'
    elseif state == 2 then
        stateState = 'WIFI'
    end

    content:text('net status:' .. stateState)
end)
window:addView(closeBtn)

