---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tamer.
--- DateTime: 2018/7/17 21:22
---

local screen_w =window:width() +30
local screen_h =window:height()
collectionView =  CollectionView()
collectionView:frame(Rect(-15,0,screen_w, screen_h))


itemSpacing=30
lineSplace=15
cellWidth= (screen_w-itemSpacing) / 3 - itemSpacing
cellHeight= 200
normalSize = Size(cellWidth,200)

--- layout
layout = CollectionViewLayout()
layout:itemSize(normalSize)
layout:lineSpacing(lineSplace)
layout:itemSpacing(itemSpacing)
collectionView:layout(layout)
--- adapter
adapter = CollectionViewAdapter()
adapter:sectionCount(function()
    return 2
end)
adapter:rowCount(function(sectionidx)
    if sectionidx == 1 then
        return 1
    else
        return 99
    end
end)
adapter:initCell(function(cell)
    local contentView = cell.contentView
    contentView:bgColor(Color(57, 175, 202, 1))
    local width = contentView:width()
    local height = contentView:height()
    cell.label = Label()
    cell.label:textAlign(TextAlign.CENTER)
    cell.label:lines(0)
    contentView:addView(cell.label)
    cell.image = ImageView()
    cell.image:width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT)
    contentView:addView(cell.image)
end)
adapter:fillCellData(function(cell, section, row)
    local contentView = cell.contentView
    local width = contentView:width()
    local height = contentView:height()
    cell.image:image("my.jpg")
    cell.image:cornerRadius(width * 0.5)
    cell.label:text("Reuse cell | section" .. section .. "row" .. row)
end)
adapter:selectedRow(function(cell, section, row)
    local txt = "be selected, section:" .. section .. "row:" .. row
    cell.label:text(txt)
end)

headerSize = Size(screen_w -60, 200)
adapter:sizeForCell(function(section, row)
    if section == 1 then
        return headerSize
    else
        return normalSize
    end
end)

collectionView:adapter(adapter)
window:addView(collectionView)


