---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XiongFangyu.
--- DateTime: 2019-05-28 10:52
---
print(mmos:time())
local container = View():width(MeasurementType.MATCH_PARENT):height(300)
window:addView(container)

local animView = View():width(100):height(100):setGravity(Gravity.CENTER):bgColor(Color(255,255,100,1))
container:addView(animView)

local btnCon = LinearLayout(LinearType.VERTICAL):width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT):marginTop(300):bgColor(Color(0,0,0,1))
window:addView(btnCon)

local gray = Color(100,100,100,1)

function startCallback()
    print("some anim start")
end
function endCallback(isFinished)
    print("some anim end", isFinished)
end
function repeatCallback()
    print("some anim repeat")
end

function setCallback(anim)
    anim:setStartCallback(startCallback)
    anim:setEndCallback(endCallback)
    anim:setRepeatCallback(repeatCallback)
end
function setAnim(anim)
    anim:setRepeat(RepeatType.NONE, -1)
    anim:setAutoBack(true)
    anim:setDuration(1)
    anim:setDelay(0)
    anim:setInterpolator(InterpolatorType.Linear)
end

local SAnimation = ScaleAnimation(0,1,0,1,AnimationValueType.RELATIVE_TO_SELF,0.5,AnimationValueType.RELATIVE_TO_SELF,0.5)
setAnim(SAnimation)
setCallback(SAnimation)

local scaleAnimBtn = Label():width(MeasurementType.MATCH_PARENT):height(40):text('scale anim'):bgColor(gray):marginBottom(5)
btnCon:addView(scaleAnimBtn)
scaleAnimBtn:onClick(function ()
    animView:clearAnimation()
    animView:startAnimation(SAnimation)
end)

local RAnimation = RotateAnimation(0,360,AnimationValueType.RELATIVE_TO_SELF,0.5,AnimationValueType.RELATIVE_TO_SELF,0.5)
setAnim(RAnimation)
setCallback(RAnimation)
local rotateAnimBtn = Label():width(MeasurementType.MATCH_PARENT):height(40):text('rotate anim'):bgColor(gray):marginBottom(5)
btnCon:addView(rotateAnimBtn)
rotateAnimBtn:onClick(function ()
    animView:clearAnimation()
    animView:startAnimation(RAnimation)
end)

local AAnimation = AlphaAnimation(0,1)
setAnim(AAnimation)
setCallback(AAnimation)
local AlphaAnimBtn = Label():width(MeasurementType.MATCH_PARENT):height(40):text('alpha anim'):bgColor(gray):marginBottom(5)
btnCon:addView(AlphaAnimBtn)
AlphaAnimBtn:onClick(function ()
    animView:clearAnimation()
    animView:startAnimation(AAnimation)
end)

local TAnimation = TranslateAnimation(AnimationValueType.RELATIVE_TO_SELF,-1,AnimationValueType.RELATIVE_TO_SELF,1,
        AnimationValueType.RELATIVE_TO_SELF,-1,AnimationValueType.RELATIVE_TO_SELF,1)
setAnim(TAnimation)
setCallback(TAnimation)
local TranslateAnimBtn = Label():width(MeasurementType.MATCH_PARENT):height(40):text('translate anim'):bgColor(gray):marginBottom(5)
btnCon:addView(TranslateAnimBtn)
TranslateAnimBtn:onClick(function ()
    animView:clearAnimation()
    animView:startAnimation(TAnimation)
end)

local AnimationS = AnimationSet(true)
AnimationS:setRepeat(RepeatType.FROM_START, 1):setAutoBack(true):setDuration(2):setInterpolator(InterpolatorType.Accelerate)
AnimationS:setStartCallback(function ()
    print('animation set start')
end)
AnimationS:setEndCallback(function (f)
    print('animation set end', f)
end)
AnimationS:setRepeatCallback(function ()
    print('animation set repeat')
end)
AnimationS:addAnimation(SAnimation:clone()):addAnimation(RAnimation:clone()):addAnimation(AAnimation:clone()):addAnimation(TAnimation:clone())
local AnimSetBtn = Label():width(MeasurementType.MATCH_PARENT):height(40):text('anim set'):bgColor(gray):marginBottom(5)
btnCon:addView(AnimSetBtn)
AnimSetBtn:onClick(function ()
    animView:clearAnimation()
    animView:startAnimation(AnimationS)
end)