---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by David.
--- DateTime: 2018/12/12 上午11:09
---

screen_w = window:width()
screen_h = window:height()

dataSource = {'https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a4b3d7085dee3d6d2293d48b252b5910/0e2442a7d933c89524cd5cd4d51373f0830200ea.jpg',
              'https://ss0.baidu.com/-Po3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a41eb338dd33c895a62bcb3bb72e47c2/5fdf8db1cb134954a2192ccb524e9258d1094a1e.jpg',
              'http://c.hiphotos.baidu.com/image/w%3D400/sign=c2318ff84334970a4773112fa5c8d1c0/b7fd5266d0160924c1fae5ccd60735fae7cd340d.jpg'}
scrollView = ScrollView(false,true)
window:addView(scrollView)
scrollView:marginLeft(0):marginTop(64)

baseLayout = LinearLayout(LinearType.VERTICAL)
baseLayout:width(screen_w):marginLeft(0):marginTop(0):height(MeasurementType.WRAP_CONTENT)
scrollView:addView(baseLayout)

adapter = ViewPagerAdapter()
adapter:getCount(function(section)
    if not(dataSource) then
        return 0
    end
    return #dataSource
end)

adapter:initCell(function(cell,row)
    print('打印一下执行次数')
    local contentView = cell.contentView
    contentView:bgColor(Color(255, 255, 255, 1))
    cell.imageView = ImageView()
    cell.imageView:contentMode(0)
    cell.imageView:marginLeft(0):marginTop(0):width(contentView:width()):height(contentView:height())
    contentView:addView(cell.imageView)
end)


adapter:fillCellData(function(cell,row)
    local contentView = cell.contentView
    local width = contentView:width()
    local height = contentView:height()

    cell.imageView:frame(Rect(0, 0, width, height))

--[[    cell.image:width(width)
    cell.image:height(height)]]


    local item =  dataSource[row % 3]
    cell.imageView:image("http://seopic.699pic.com/photo/50034/3685.jpg_wh1200.jpg")
end)

viewPager = ViewPager()
viewPager:endDragging(function(row)
    -- print('停止滚动了----',row)
end)

baseLayout:addView(viewPager)

viewPager:marginLeft(0):marginTop(0):width(screen_w):height(320)
viewPager:autoScroll(true)
viewPager:recurrence(true)

viewPager:showIndicator(true)

viewPager:adapter(adapter)

viewPager:reloadData()

-- 点击十万好书头
local changeHeaderLayout = LinearLayout()
changeHeaderLayout:marginLeft(0):marginTop(10):width(screen_w)
changeHeaderLayout:bgColor(Color(255,0,0,1))
baseLayout:addView(changeHeaderLayout)


local descLabel = Label()
descLabel:text("点击上十万的好书")
descLabel:setWrapContent(true)
descLabel:marginLeft(10)
changeHeaderLayout:addView(descLabel)
--
local clickChangeView = View()
changeHeaderLayout:addView(clickChangeView)
clickChangeView:width(screen_w-150):height(20)

local clickChangeLayout = LinearLayout()
clickChangeLayout:width(MeasurementType.WRAP_CONTENT)
clickChangeLayout:marginRight(10):setGravity(Gravity.RIGHT)
clickChangeView:addView(clickChangeLayout)
--
local changeImage = ImageView()
changeImage:image('https://s.momocdn.com/w/u/others/2018/07/19/1531993269660-guifushengongdexiagutupian-001.jpg')
changeImage:marginLeft(0):marginTop(0):width(15):height(15)
clickChangeLayout:addView(changeImage)

local changeTitle = Label()
changeTitle:text('换一换')
clickChangeLayout:addView(changeTitle)

local bodyLayout = LinearLayout(LinearType.VERTICAL)
bodyLayout:width(screen_w):height(MeasurementType.WRAP_CONTENT)
baseLayout:addView(bodyLayout)

-- local BKHeaderBook =  require('Book.BKHeaderBook')
-- local headerBook = BKHeaderBook:new()
-- headerBook:init(bodyLayout)
-- headerBook:update('https://ss0.baidu.com/-Po3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a41eb338dd33c895a62bcb3bb72e47c2/5fdf8db1cb134954a2192ccb524e9258d1094a1e.jpg',
--         '都市鬼谷子','作者:陈俊大魔王','身居鬼谷玄道的鬼谷子是真牛逼啊','转载中..549.64万字')

local bookListLayout = LinearLayout()
bookListLayout:width(screen_w):height(MeasurementType.WRAP_CONTENT)
bodyLayout:addView(bookListLayout)

-- local BKBookView = require('Book.BKBookView')
-- local bookView1 = BKBookView:new()
-- bookView1:init(bookListLayout)
-- bookView1:update('都市喜剧王','https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a4b3d7085dee3d6d2293d48b252b5910/0e2442a7d933c89524cd5cd4d51373f0830200ea.jpg')

-- local bookView2 = BKBookView:new()
-- bookView2:init(bookListLayout)
-- bookView2:update('都市喜剧王','https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a4b3d7085dee3d6d2293d48b252b5910/0e2442a7d933c89524cd5cd4d51373f0830200ea.jpg')

-- local bookView3 = BKBookView:new()
-- bookView3:init(bookListLayout)
-- bookView3:update('都市喜剧王','https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a4b3d7085dee3d6d2293d48b252b5910/0e2442a7d933c89524cd5cd4d51373f0830200ea.jpg')

local labelN = Label()
labelN:text('3-041-05913-0591-591-05910-5910-591-0591-591-591-0591-0591-591-51-59105910-951-0591-53-041-05913-0591-591-05910-5910-591-0591-591-591-0591-0591-591-51-59105910-951-0591-53-041-05913-0591-591-05910-5910-591-0591-591-591-0591-0591-591-51-59105910-951-0591-5')
labelN:width(200):height(MeasurementType.WRAP_CONTENT)
labelN:lines(0)
baseLayout:addView(labelN)

-- local bookView3 = BKBookView:new()
-- bookView3:init(baseLayout)
-- bookView3:update('都市喜剧王','https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a4b3d7085dee3d6d2293d48b252b5910/0e2442a7d933c89524cd5cd4d51373f0830200ea.jpg')


print('........................-------------------....'..baseLayout:height())
print(scrollView:contentSize():height())

baseLayout:onClick(function()
    print('........................-------------------....'..baseLayout:height())
end)


