---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by weimingchuan.
--- DateTime: 2018/8/15 下午4:44
---
--3D聊天室的创建界面
--
--datasouce = {
--    headIconName = "http://img.momocdn.com/album/4F/CF/4FCFA0D2-95E8-3C09-3760-142E6916CA1B20170701_S.jpg",
--    summary = "安全等级：高",
--    sections = {
--        {
--            sectionTitle = "通过以下设置可以提高安全等级",
--            items = {
--                {
--                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
--                    title = "密码修改——1——100",
--                    subtitle = nil,
--                    height=100,
--                },
--                {
--                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
--                    title = "手机绑定——2——300",
--                    subtitle = "已绑定",
--                    height=300,
--                },
--                {
--                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
--                    title = "证件信息——3——100",
--                    subtitle = "未绑定",
--                    height=100,
--                },
--                {
--                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
--                    title = "登录保护--4--100",
--                    subtitle = "已开启",
--                    height=100,
--                },
--                {
--                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
--                    title = "账号注销--5--200",
--                    subtitle = "",
--                    height=200,
--                },
--                {
--                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
--                    title = "密码修改--6--300",
--                    subtitle = nil,
--                    height=300,
--                },
--            }
--        },
--
--    }
--}
--
--
--local size = System:screenSize();
----local statusBarHeight = System:stateBarHeight()
--local statusBarHeight = 16
--local screen_w, screen_h = size:width(), size:height()
--local titleHeight = 56;
--local marginLeft = 61;
--print("屏幕的宽高：", screen_w, screen_h)
--
----设置背景
--local imageView = ImageView();
--imageView:image("bg_chat_3d_match")
--imageView:contentMode(ContentMode.SCALE_TO_FILL)
--imageView:width(screen_w)
--imageView:height(screen_h)
--window:addView(imageView)
--
----返回按钮
--local backImageView = ImageView();
--backImageView:image("ic_chat_3d_create_chat_back")
--backImageView:contentMode(ContentMode.SCALE_TO_FILL)
--backImageView:width(86)
--backImageView:height(28)
--backImageView:onClick(function()
--    print('点击了返回')
--end)
--window:addView(backImageView)
--
--
----场景选择的标题
--local sceneLabelTitle = Label();
--sceneLabelTitle:width(64)
--sceneLabelTitle:height(22)
--sceneLabelTitle:x(marginLeft)
--sceneLabelTitle:y(40)
--sceneLabelTitle:textAlign(TextAlign.LEFT)
--sceneLabelTitle:text("场景选择")
--sceneLabelTitle:fontSize(16);
--sceneLabelTitle:textColor(Color(255, 255, 255, 1))
--window:addView(sceneLabelTitle)
--
----横向的列表
--local collectionView = CollectionView()
----collectionView:bgColor(Color(255, 0, 0, 1))
--collectionView:width(screen_w - 60 * 2)
--collectionView:height(88)
--collectionView:x(60)
--collectionView:y(70)
--
--local collectionViewLayout = CollectionViewLayout();
--collectionViewLayout:lineSpacing(0);
--collectionViewLayout:itemSpacing(10);
--collectionViewLayout:itemSize(Size(80, 80))
--collectionView:layout(collectionViewLayout)
--local collectionViewAdapter = CollectionViewAdapter();
--collectionView:adapter(collectionViewAdapter)
--window:addView(collectionView)
--
--local collectionView2 = Label();
--collectionView2:bgColor(Color(255, 0, 0, 1))
--collectionView2:width(screen_w - 60 * 2)
--collectionView2:height(88)
--collectionView2:x(60)
--collectionView2:y(70)
--window:addView(collectionView2)
--
--
----向左翻页
--local leftImageView = ImageView();
--leftImageView:image("ic_chat_3d_create_chat_arrow_left")
--leftImageView:contentMode(ContentMode.SCALE_TO_FILL)
--leftImageView:width(32)
--leftImageView:height(32)
--leftImageView:x(16)
--leftImageView:y(98)
--window:addView(leftImageView)
--
----向右翻页
--local rightImageView = ImageView();
--rightImageView:image("ic_chat_3d_create_chat_arrow_right")
--rightImageView:contentMode(ContentMode.SCALE_TO_FILL)
--rightImageView:width(32)
--rightImageView:height(32)
--rightImageView:x(screen_w - 48)
--rightImageView:y(98)
--window:addView(rightImageView)
--
----聊天室主题
--local chatTitle = Label();
--chatTitle:width(220)
--chatTitle:height(22)
--chatTitle:x(marginLeft)
--chatTitle:y(172)
--chatTitle:textAlign(TextAlign.LEFT)
--chatTitle:text("聊天室主题")
--chatTitle:fontSize(16);
--chatTitle:textColor(Color(255, 255, 255, 1))
--window:addView(chatTitle)
--
----输入自定义主题
--local editTextView = EditTextView();
--editTextView:width(240)
--editTextView:height(36)
----editTextView:bg("bg_chat_3d_create_chat_input")
--editTextView:x(marginLeft)
--editTextView:y(202)
--editTextView:placeholder("输入自定义主题")
--editTextView:textAlign(TextAlign.LEFT)
--editTextView:fontSize(12);
--editTextView:textColor(Color(255, 0, 0, 1))
--editTextView:placeholderColor(Color(255, 0, 0, 1))
--window:addView(editTextView)
--
----随机主题
--local randomTitle = ImageView();
--randomTitle:image("ic_chat_3d_create_chat_random_title")
--randomTitle:contentMode(ContentMode.SCALE_TO_FILL)
--randomTitle:width(36)
--randomTitle:height(36)
--randomTitle:x(320)
--randomTitle:y(203)
--randomTitle:onClick(function()
--    print("随机主题")
--end)
--window:addView(randomTitle)
--
----创建房间
--local createRoom = ImageView();
--createRoom:image("ic_chat_3d_create_chat_room")
--createRoom:contentMode(ContentMode.SCALE_TO_FILL)
--createRoom:width(132)
--createRoom:height(40)
--createRoom:x(268)
--createRoom:y(319)
--createRoom:onClick(function()
--    print("点击了创建房间")
--end)
--window:addView(createRoom)


print("|| lua ")
local typeCollectionView = CollectionView()
typeCollectionView:frame(Rect(10, 254, 200, 66))
--typeCollectionView:bgColor(Color(255, 0, 0, 0))
typeCollectionView:scrollDirection(1)
local adapter = CollectionViewAdapter()
print("|| lua adapter")

adapter:reuseId(function (section, row)
    return "1"
end)

adapter:initCell(function (cell)
    local contentView = cell.contentView
    local width = contentView:width()
    local height = contentView:height()
    print(width)
    print(height)
    contentView:cornerRadius(6)
    contentView:bgColor(Color(255, 0, 0, 1))
    --cell.imageView = ImageView()
    --cell.imageView:image("bg_chat_3d_create_chat_type")
    --cell.imageView:frame(Rect(4, 4, width-8, height-8))
    --contentView:addView(cell.imageView)

    cell.nameLabel = Label();
    cell.nameLabel:width(width)
    cell.nameLabel:height(height)
    cell.nameLabel:textAlign(TextAlign.CENTER)
    cell.nameLabel:fontSize(12);
    cell.nameLabel:textColor(Color(255, 255, 255, 1))
    --cell.nameLabel:frame(Rect(4, 4, width-8, height-8))
    contentView:addView(cell.nameLabel)

end)
local sceneTypeNames = {"八卦","交友","旅游","美食","健身","娱乐","游戏","体育","……"}
adapter:fillCellData(function (cell,section,row)
    print("jiazaicell:   ",row)
    print(sceneTypeNames[row])
    cell.nameLabel:text(sceneTypeNames[row])
end)
adapter:sectionCount(function ()
    return 1
end)
adapter:rowCount(function (section)
    --找到对应的组
    return 9
end)
adapter:selectedRow(function (cell,section,row)
    print('onclick', section,row)
end)
local layout = CollectionViewLayout()
layout:lineSpacing(5)
layout:itemSpacing(10)
layout:itemSize(Size(48, 36))
typeCollectionView:layout(layout)
typeCollectionView:adapter(adapter)
typeCollectionView:showScrollIndicator(true)
--typeCollectionView:adapter(adapter)
window:addView(typeCollectionView)

e = EditTextView()
e:width(100)
e:height(100)
e:padding(0,0,0,10)
window:addView(e)