---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhang.ke.
--- DateTime: 2018/11/30 下午2:34
---

demoUtils = require("momolua.demoUtils.DemoUtils")

local _class = {}
_class._version = '1.0'
_class._classname = 'DBUtils'

function _class:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self

    return o
end

function _class:onCreate(contentView)

    local width = contentView:width()
    local height = contentView:height()
    local showView = View():width(width):height(height - 100):y(100)
    contentView:addView(showView)

    local Desc = Label():text("数量：0"):fontSize(19):setAutoFit(true):height(40):textAlign(TextAlign.CENTER):textColor(Color(0, 0, 0, 1)):x(10):y(50)
    contentView:addView(Desc)
    --初始化view

    ----Demo 实践------

    local dataSource = Array()

    local tableView = TableView()
    tableView:width(showView:width())
    tableView:height(showView:height())
    showView:addView(tableView)

    local adapter = TableViewAdapter()
    tableView:adapter(adapter)
    adapter:sectionCount(function()
        return 1
    end)
    adapter:rowCount(function(sectionsID)
        return dataSource:size()
    end)
    adapter:reuseId(function(section, row)
        return 'a'
    end)
    adapter:initCellByReuseId('a', function(cell)
        local v = cell.contentView
        v:bgColor(Color(255, 0, 0, 0.15))
        cell.label = Label()
        cell.label:textColor(Color(255, 255, 255, 1))
        cell.label:fontSize(20)
        cell.label:lines(0)
        cell.label:bgColor(Color(0, 0, 0, 0.15))
        cell.label:marginTop(5):width(width)
        cell.contentView:addView(cell.label)
    end)

    adapter:fillCellDataByReuseId('a', function(cell, sectionId, row)
        local item = dataSource:get(row)
        -- if item then
        cell.label:text("feildA: " .. item:fieldA() .. " , feildB: " .. item:fieldB())
        -- end
    end)

    adapter:heightForCell(function(section, row)
        local item = dataSource:get(row)
        if (item:fieldA() > 10) then
            return 80;
        else
            return 40;
        end
    end)

    function _class:newItem(num, text)
        local db = TestDB()
        db:fieldA(num)
        db:fieldB(text)
        return db
    end

    function _class:insertMessage(num, text)
        dataSource:add(_class:newItem(num, text))
        tableView:insertCellAtRow(dataSource:size(), 1)
        Desc:text("数量："..dataSource:size())
    end

    function _class:deleteMessage(index)
        dataSource:remove(index)
        tableView:deleteCellAtRow(index,1)
        Desc:text("数量："..dataSource:size())
    end

    function _class:queryMessage()
        local start = os.time()
        local dblist = DBUtils:queryList(TestDB())
        if dblist then
            print('get from db ', (os.time() - start))
            dataSource = dblist
            tableView:reloadData()
            Desc:text("数量："..dataSource:size())
        else
            print('read from db failed')
        end
    end

    _class:queryMessage()

    ----Demo 实践------

    ----以上代码不用管，显示UI用的

    local btnInfo = { "new item", "insert list", "delete", "query" }

    local tabsContainer = demoUtils:createCommonTabLinearLayout(contentView)
    local tabs = demoUtils:addTabFromData(btnInfo, tabsContainer)

    for i, v in pairs(tabs) do
        if i == btnInfo[1] then
            v:onClick(function()
                local num = math.random(20)
                local text = 't:'
                for i = 1, num do
                    text = text .. 'aa'
                end
                _class:insertMessage(num, text)
            end)
        elseif i == btnInfo[2] then
            v:onClick(function()
                local start = os.time()
                local success = DBUtils:insertList(dataSource)
                _class:queryMessage()
                print('save list to db ', success, (os.time() - start))

            end)
        elseif i == btnInfo[3] then
            v:onClick(function()
                if dataSource:size() > 0 then
                    local data = dataSource:get(1)
                    local start = os.time()
                    local success = DBUtils:delete(data)
                    print('delete from db ', success, (os.time() - start))
                    if success then
                        _class:queryMessage()
                    end
                end
            end)
        elseif i == btnInfo[4] then
            v:onClick(function()
                _class:queryMessage()
            end)
        end
    end

end

_class:onCreate(window)

return _class