---
--- Generated by Momo 
--- Created by MOMO.
--- DateTime: 2019/1/16
---

dataSource = { 'https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a4b3d7085dee3d6d2293d48b252b5910/0e2442a7d933c89524cd5cd4d51373f0830200ea.jpg', 'https://ss0.baidu.com/-Po3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a41eb338dd33c895a62bcb3bb72e47c2/5fdf8db1cb134954a2192ccb524e9258d1094a1e.jpg', 'http://c.hiphotos.baidu.com/image/w%3D400/sign=c2318ff84334970a4773112fa5c8d1c0/b7fd5266d0160924c1fae5ccd60735fae7cd340d.jpg' }

local titles = Array()
titles:add("标题一")
titles:add("标题二")
titles:add("标题三")

tabSegment = TabSegmentView(Rect(0, 100, window:width() - 100, 50), titles, Color(121, 121, 121, 1.0))
tabSegment:setAlignment(TabSegmentAlignment.RIGHT)

tabSegment:normalFontSize(20.7)

tabSegment:selectedColor(Color(255,0,0,1))

print('----------normalfontsize = ',tabSegment:normalFontSize())


window:addView(tabSegment)

--tabSegment:setTabSelectedListener(function(index)
--    print("点击", index)
--end)

--tabSegment:setItemTabClickListener(function(index)
--    print("Click", index)
--end)

adapter = ViewPagerAdapter()
adapter:getCount(function(section)
    return #dataSource
end)

adapter:initCell(function(cell, row)
    print('打印一下执行次数')
    local contentView = cell.contentView
    contentView:bgColor(Color(255, 255, 255, 1))
    cell.imageView = ImageView()
    cell.imageView:contentMode(0)
    cell.imageView:frame(Rect(0, 0, width, height))
    contentView:addView(cell.imageView)
end)
adapter:fillCellData(function(cell, row)
    local contentView = cell.contentView
    local width = contentView:width()
    local height = contentView:height()
    cell.imageView:frame(Rect(0, 0, width, height))
    local item = dataSource[row]
    cell.imageView:image(item)
end)

viewPager = ViewPager()

viewPager:endDragging(function(row)
    -- print('停止滚动了----',row)
end)
window:addView(viewPager)
width = window:width()
height = window:height()
viewPager:marginTop(150):width(window:width() - 100):height(window:height() - 150)

--viewPager:autoScroll(false)
viewPager:showIndicator(true)

viewPager:adapter(adapter)

tabSegment:relatedToViewPager(viewPager, true)
window:addView(viewPager)

actionContainer = LinearLayout(LinearType.VERTICAL):setGravity(Gravity.RIGHT)
actionContainer:marginTop(100):width(MeasurementType.WRAP_CONTENT):height(MeasurementType.MATCH_PARENT)
actionContainer:bgColor(Color(12, 23, 222, 1.0))
window:addView(actionContainer)

action1 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action1:text("滚动到第二个")
actionContainer:addView(action1)
action1:onClick(function()
    tabSegment:setCurrentIndexAnimated(2, true)
end)

action2 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action2:text("设置红点展示")
actionContainer:addView(action2)
action2:onClick(function()
    tabSegment:setRedDotHiddenAtIndex(1, false)
end)

action3 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action3:text("设置红点隐藏")
actionContainer:addView(action3)
action3:onClick(function()
    tabSegment:setRedDotHiddenAtIndex(1, true)
end)

action4 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action4:text("设置布局居中")
actionContainer:addView(action4)
action4:onClick(function()
    tabSegment:setAlignment(TabSegmentAlignment.CENTER)
end)

action5 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action5:text("设置布局居左")
actionContainer:addView(action5)
action5:onClick(function()
    tabSegment:setAlignment(TabSegmentAlignment.LEFT)
end)

action6 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action6:text("设置布局居右")
actionContainer:addView(action6)
action6:onClick(function()
    tabSegment:setAlignment(TabSegmentAlignment.RIGHT)
end)

action7 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action7:text("设置标注文本")
actionContainer:addView(action7)
action7:onClick(function()
    tabSegment:setTapBadgeTitleAtIndex("呵呵", 3)
end)

action8 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action8:text("隐藏标注文本")
actionContainer:addView(action8)
action8:onClick(function()
    tabSegment:setTapBadgeTitleAtIndex(nil, 3)
end)

action9 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action9:text("设置标注数字")
actionContainer:addView(action9)
action9:onClick(function()
    tabSegment:setTapBadgeNumAtIndex(121, 3)
end)

action10 = Label():bgColor(Color(255, 255, 255, 1.0)):marginTop(10)
action10:text("隐藏标注数字")
actionContainer:addView(action10)
action10:onClick(function()
    tabSegment:setTapBadgeNumAtIndex(0, 3)
end)
