

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by David.
--- DateTime: 2018/7/11 下午4:52
---

window:viewAppear(function()
    print("|| window")
    print(window:getExtra():get("key"))
end)

clickTime = 0;
baseView = View()
baseView:frame(Rect(0, 0, 200, 300))
--baseView:getCSS():position(1):top(0):left(0):width(200):height(300)
--baseView:frame(Rect(0,0,200,300))
--window:addView(baseView)
window:addView(baseView)
local color = Color(123, 123, 123, 1)
baseView:bgColor(color)
baseView:onClick(function()
    print('12345')
    clickTime = clickTime+1
    local text =  string.format('你点了我%d次',clickTime)
    label:text(text)
    transView:bgColor(Color(124,21,214,1.0))
end
)

otherView = View()
--otherView:frame(Rect(0,300,100,100))
local color = Color(123, 123, 123, 1)
otherView:bgColor(color)
--window:addView(otherView)
otherView:frame(Rect(0, 300, 100, 100))
-- otherView:getCSS():position(1):top(300):left(0):width(100):height(100)
window:addView(otherView)

label = Label():text(string.format('你点了我%d次',clickTime))
-- local color = Color(202, 12, 56, 1)
label:bgColor(Color():clear())
--label:frame(Rect(100,500,100,20))
label:fontSize(12)
--window:addView(label)
window:addView(label)
label:frame(Rect(100, 500, 100, 20))
-- label:getCSS():position(1):top(500):left(100):width(100):height(20)

label:borderWidth(1)
local color = Color(99, 123, 1, 1)
label:borderColor(color)
label:textAlign(TextAlign.CENTER)
label:setGradientColor(Color(28,173,255,1),Color(147,201,106,1),true)

-- window:flexLayout()


transView = Label():text("???")
transView:frame(Rect(200,100,50,50))
transView:bgColor(Color(125,211,2,1.0))
transView:openRipple(true)
window:addView(transView)

-- transView:anchorPoint(0.8,0.2)

transView:transform(45 , false)

sendView = View()
sendView:frame(Rect(200,100,20,20))
-- sendView:bgColor(Color():setAColor("#9dff66cc"))
sendView:bgColor(Color(0,0,0,1))
window:addView(sendView)


window:onClick(function()
    -- transView:transform(-22.5 , true)

--    transView:scale(2,2)
    --transView:translation(2,2)
    transView:rotation(30)

    window:sendSubviewToBack(sendView)

     --window:bringSubviewToFront(transView)
end)

transView:onTouch(function(x,y)
    print("点击了x:",x.." y:",y)

    transView:transformIdentity()
end)


