---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XiongFangyu.
--- DateTime: 2019-07-01 18:44
---

local clz = luajava.bindClass('com.xfy.demo.common.JavaClassTest')
print(clz:getInt())
clz:doSomeThing('lua string')

local obj = luajava.new(clz)
print('init : ', obj:aInt(), obj:aFloat())
obj['aInt'] = 3
obj['aFloat'] = 4.2

print('after : ', obj:aInt(), obj:aFloat())