
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by David.
--- DateTime: 2018/9/4 下午8:00
---

dataSource = {'https://ss2.baidu.com/-vo3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a4b3d7085dee3d6d2293d48b252b5910/0e2442a7d933c89524cd5cd4d51373f0830200ea.jpg','https://ss0.baidu.com/-Po3dSag_xI4khGko9WTAnF6hhy/super/whfpf%3D425%2C260%2C50/sign=a41eb338dd33c895a62bcb3bb72e47c2/5fdf8db1cb134954a2192ccb524e9258d1094a1e.jpg','http://c.hiphotos.baidu.com/image/w%3D400/sign=c2318ff84334970a4773112fa5c8d1c0/b7fd5266d0160924c1fae5ccd60735fae7cd340d.jpg'}



adapter = ViewPagerAdapter()
adapter:getCount(function(section)
    print("keye s",tostring(#dataSource))
    return #dataSource
end)

kScreenWidth        = System:screenSize():width()
kScreenHeight       = System:screenSize():height()
print("keye1")
adapter:initCell(function(cell,row)
    print("keye 11")
    print('打印一下执行次数')
    local contentView = cell.contentView
    contentView:bgColor(Color(255, 255, 255, 1))
    cell.imageView = ImageView()
    -- cell.imageView:contentMode(0)
    cell.imageView:contentMode(ContentMode.SCALE_ASPECT_FILL)
    --  cell.imageView:frame(Rect(0, 0, width, height))
    cell.imageView:width(kScreenWidth):height(kScreenHeight)
    --    cell.imageView:frame(Rect(0, 0, width, height))
    contentView:addView(cell.imageView)
end)
adapter:fillCellData(function(cell,row)
    print("keye 22")
    print("cell size width:",width," height:",height)
    local item =  dataSource[row]
    cell.imageView:image(item)
end)

-- viewPager = ViewPager():width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT)
viewPager = ViewPager():marginLeft(100):marginTop(100):width(200):height(500)
viewPager:bgColor(Color(123,123,123,1))
--viewPager = ViewPager():width(200):height(500)
print("keye3")
viewPager:autoScroll(true)
viewPager:recurrence(true)
viewPager:showIndicator(true)
viewPager:endDragging(function(row)
    -- print('停止滚动了----',row)
end)
window:addView(viewPager)
width =  window:width()
height = window:height()

viewPager:adapter(adapter)
print("keye4")

viewPager:reloadData()
otherView = View()
--otherView:frame(Rect(0,300,100,100))
local color = Color(123, 123, 123, 1)

