---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XiongFangyu.
--- DateTime: 2018/10/23 上午11:21
---

--执行错误
--local nilValue = nil
--nilValue:a()

local btn = View():width(50):height(50):bgColor(Color(0,0,0,1)):onClick(function ()
    --call nil
    --local nilValue = nil
    --nilValue:a()

    -- error action
    --local a = 'a'
    --a = 1 + a;
end)

window:addView(btn)