---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/12/18 下午5:51
---
affinity("keye")
----momoLua SDK UI测试Demo
----任何改动后，建议跑一下demo测试。并且即使更新demo

local reTime=os.time()*1000
local  haha=require("momolua.MomoLua",true)
print("momolua.MomoLua: ",os.time()*1000-reTime)
Navigator:gotoPage("http://172.16.103.77/~momo/momolua.zip",nil,1)