---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/8/30 下午3:09
---


datasouce = {
    headIconName = "http://img.momocdn.com/album/4F/CF/4FCFA0D2-95E8-3C09-3760-142E6916CA1B20170701_S.jpg",
    summary = "安全等级：高",
    sections = {
        {
            sectionTitle = "通过以下设置可以提高安全等级",
            items = {
                {
                    iconName = "http://seopic.699pic.com/photo/50035/0520.jpg_wh1200.jpg",
                    title = "密码修改——1——100",
                    subtitle = nil,
                    height = 100,
                },
                {
                    iconName = "http://seopic.699pic.com/photo/50027/8874.jpg_wh1200.jpg",
                    title = "手机绑定——2——300",
                    subtitle = "已绑定",
                    height = 300,
                },
                {
                    iconName = "http://seopic.699pic.com/photo/50042/3858.jpg_wh1200.jpg",
                    title = "证件信息——3——100",
                    subtitle = "未绑定",
                    height = 100,
                },
                {
                    iconName = "http://seopic.699pic.com/photo/50034/3685.jpg_wh1200.jpg",
                    title = "登录保护--4--100",
                    subtitle = "已开启",
                    height = 100,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "登录保护--4--100",
                    subtitle = "已开启",
                    height = 100,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "登录保护--4--100",
                    subtitle = "已开启",
                    height = 100,
                },
            }
        },

    }
}
size = 6

local viewPager = ViewPager()
viewPager:y(20):width(window:width()):height(window:height() - 20)
--viewPager:setPreRenderCount(0)
viewPager:bgColor(Color(255,0,0,1))

Toast('aheadLoad === '..tostring(viewPager:aheadLoad()))

--viewPager:currentPageColor(Color(255, 0, 0, 1))
--viewPager:pageDotColor(Color(200, 120, 120, 1))

 --viewPager:showIndicator(false)



local adapter = ViewPagerAdapter()

adapter:getCount(function()
    return size;
end)

adapter:reuseId(function(p)
    return '1'
end)

adapter:initCellByReuseId('1', function(cell, position)
     print('init', position)
    local normalCell = require("cells.ViewPagerCell")
    normalCell:onCreate(cell, nil)
end)

adapter:fillCellDataByReuseId('1', function(cell, position)
    print('fill', position)
    local normalCell = require("cells.ViewPagerCell")
    local section = datasouce.sections[1]
    local items = section.items;
    local detailItem = items[position]
    normalCell:onLayout(cell, detailItem.iconName, position)
end)

--viewPager:autoScroll(true)
--viewPager:recurrence(true)
--viewPager:frameInterval(2)
-- viewPager:showIndicator(true)
--viewPager:autoScroll(true)
--viewPager:frameInterval(5)


viewPager:endDragging(function(position)
    -- print("endDragging -- ", position)
end)

viewPager:setPageClickListener(function(position)
    -- Toast("click position: " .. tostring(position), 1)

    Toast("currentPage =  " .. tostring(viewPager:currentPage()), 1)

    --print('click position: '.. position)
end)


--viewPager:enabled(false)









viewPager:cellWillAppear(function(cell, position)
    print("  Appear ==---- ", position)
end)


--viewPager:scrollToPage(3,true)


viewPager:adapter(adapter)

window:addView(viewPager)

local array = Array()
array:add('附近动态')
array:add('附近的人')
array:add('附近直播')
array:add('item4')
array:add('item5')
array:add('item6')


-- tabLayout = TabSegmentView(Point(0, 20), array,Color(255,12,255,1))
tabLayout = TabSegmentView(Rect(0, 0, window:width() - 100, 50), array, Color(255, 12, 255, 1))

tabLayout:relatedToViewPager(viewPager,false)

--viewPager:setTabScrollingListener(function(progress,fromIndex,toIndex)
--    print(' from =  ',fromIndex, '  to = ', toIndex )
--end)

tabLayout:setTabScrollingListener(function(progress,fromIndex,toIndex)
    --print(' from =  ',fromIndex, '  to = ', toIndex )
end)



tabLayout:setTabSelectedListener(function(index)
    Toast("select f.." .. index, 1)
end)

--tabLayout:bgColor(Color():hex(0xffff00):alpha(1))

tabLayout:selectScale(20 / 15)
tabLayout:normalFontSize(15)
tabLayout:setTapBadgeNumAtIndex(30, 3)

tabLayout:setTapBadgeNumAtIndex(30, 3)

tabLayout:setRedDotHiddenAtIndex(2)

viewPager:padding(50, 0, 0, 0)
window:addView(tabLayout)

local label4 = Label()
label4:y(50)
label4:width(100)
label4:height(100)
label4:fontSize(16)
label4:text("mapmapmapmapmap")
label4:bgColor(Color():hex(0xffff00):alpha(1))

clickNumber = 1;
Clipboard:setTextWithClipboardName('111111', 'wu')


backKeyEnabled = true
window:backKeyEnabled(backKeyEnabled)

label4:onClick(function()


    viewPager:scrollToPage(6,false)
    --local alert = Alert()
    --        :title("确认离开房间")
    --        :message(nil)
    --        :setCancel("取消", nil)
    --        :setOk("确认", function() print("确认")  end)
    --alert:show()


    --if backKeyEnabled then
    --    window:backKeyEnabled(false)
    --    backKeyEnabled = false
    --    Toast("enabled ---- "..tostring( window:backKeyEnabled()),2)
    --else
    --    window:backKeyEnabled(true)
    --    backKeyEnabled = true
    --    Toast("enabled ---- "..tostring( window:backKeyEnabled()),2)
    --end
    --
    ----clickNumber = clickNumber + 2
    ----
    -- viewPager:scrollToPage(0,true)

    --[[    tabLayout:setCurrentIndexAnimated(2)
        tabLayout:setTapBadgeNumAtIndex(20, 4)
        tabLayout:setRedDotHiddenAtIndex(3)]]

    --tabLayout:tintColor(Color(0, 0, 255, 1))
end)

window:addView(label4)

-- viewPager:scrollToPage(2, false)



viewPager:cellDidDisappear(function(cell, position)
    print("Disappear:", position)

    --if clickNumber == 1 then
    --    print(Clipboard:getTextWithClipboardName('wu'),'------')
    --elseif clickNumber == 2 then
    --    print(Clipboard:getTextWithClipboardName('tian'),'------')
    --elseif clickNumber == 3 then
    --    print(Clipboard:getTextWithClipboardName('long'),'------')
    --end

end)

window:backKeyPressed(function()
    Toast("backKeyPressed----",2)
    print("window:backKeyPressed------")
end)




