---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XiongFangyu.
--- DateTime: 2019/2/20 4:20 PM
---

ut = UserDataTest()
print(ut:a())
print(ut:b())
print(ut:c())

print(StaticMethodTest:a())
print(StaticMethodTest:b())
print(StaticMethodTest:c())
