---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-09-05 12:05
---

_Color = {
    White = Color(255,255,255,1),
    Black= Color(0,0,0,1),
    MediumGray = Color(160, 160, 160, 1),
    DeepGray = Color(70, 70, 70,1),
    LightGray = Color(245, 245, 245,1),
    Gray = Color(130,130,130,1),
    Clear = Color(0,0,0,0),
    LightBlack = Color(60,60,60,1),
    Green = Color(0,255,0,1),
    Red = Color(255,0,0,1),
    Blue = Color(0,0,255,1)
}

_TabbarHeight = 60
_NaviBarHeight = 50