---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-09-05 12:05
---

local _class = {
    _name = "DiscoverCell",
    _version = "1.0"
}

---@public
function _class:new()
    local o = {}
    setmetatable(o, {__index = self})
    return o
end

---@public
function _class:setupCellSubviews(width)
    self.baseLayout = LinearLayout(LinearType.VERTICAL)
    self.baseLayout:width(width):height(MeasurementType.MATCH_PARENT)
    self.baseLayout:bgColor(_Color.White)

    --图片
    local imageView = ImageView():width(width):height(width)
    imageView:contentMode(ContentMode.SCALE_ASPECT_FIT)
    imageView:lazyLoad(false)
    imageView:cornerRadius(8)
    --imageView:onClick(function()
    --    Toast(self.titleLabel:text(), 1)
    --end)
    self.imageView = imageView

    --布局图片上的小图标
    local imageViewLayout = LinearLayout(LinearType.HORIZONTAL)
    imageViewLayout:marginTop(-30):width(width):height(25):setGravity(Gravity.CENTER)
    self.imageViewLayout = imageViewLayout

    local favorImageView = ImageView()
    favorImageView:marginLeft(10):width(16):height(16):setGravity(Gravity.CENTER)
    favorImageView:image("https://s.momocdn.com/w/u/others/2019/08/28/1566999785245-favor.png")
    self.favorImageView = favorImageView
    imageViewLayout:addView(favorImageView)

    local countLabel = Label()
    countLabel:marginLeft(2):width(MeasurementType.WRAP_CONTENT):height(20):setGravity(Gravity.CENTER)
    countLabel:text("53篇"):textColor(_Color.White):textAlign(TextAlign.LEFT):fontSize(10)
    self.countLabel = countLabel
    imageViewLayout:addView(countLabel)

    local lookImageView = ImageView()
    lookImageView:marginLeft(5):width(16):height(16):setGravity(Gravity.CENTER)
    lookImageView:image("https://s.momocdn.com/w/u/others/2019/08/28/1566999801782-look.png")
    self.lookImageView = lookImageView
    imageViewLayout:addView(lookImageView)

    local lookLabel = Label()
    lookLabel:marginLeft(2):width(MeasurementType.WRAP_CONTENT):height(20):setGravity(Gravity.CENTER)
    lookLabel:text("4301"):textColor(_Color.White):textAlign(TextAlign.LEFT):fontSize(10)
    self.lookLabel = lookLabel
    imageViewLayout:addView(lookLabel)

    --标题
    local titleLabel = Label()
    titleLabel:marginTop(20):width(width):height(30)
    titleLabel:textColor(_Color.Black):fontSize(14):setTextFontStyle(FontStyle.BOLD)
    titleLabel:bgColor(self.baseLayout:bgColor())
    self.titleLabel = titleLabel

    --更新内容提示
    local iconHeight = 15
    local updateLayout = LinearLayout(LinearType.HORIZONTAL)
    updateLayout:marginLeft(0):marginTop(0):width(width):height(iconHeight):setGravity(Gravity.CENTER)
    updateLayout:bgColor(_Color.Clear)
    self.updateLayout = updateLayout

    self.iconViews = {}
    local iconView1 = ImageView()
    iconView1:width(iconHeight):height(iconHeight):setGravity(Gravity.CENTER):cornerRadius(iconHeight / 2)
    iconView1:bgColor(updateLayout:bgColor())
    table.insert(self.iconViews, iconView1)
    updateLayout:addView(iconView1)

    local iconView2 = ImageView()
    iconView2:marginLeft(-5):width(iconHeight):height(iconHeight):setGravity(Gravity.CENTER):cornerRadius(iconHeight / 2)
    iconView2:bgColor(updateLayout:bgColor())
    table.insert(self.iconViews, iconView2)
    updateLayout:addView(iconView2)

    local iconView3 = ImageView()
    iconView3:marginLeft(-5):width(iconHeight):height(iconHeight):setGravity(Gravity.CENTER):cornerRadius(iconHeight / 2)
    iconView3:bgColor(updateLayout:bgColor())
    table.insert(self.iconViews, iconView3)
    updateLayout:addView(iconView3)

    local iconLabel = Label()
    iconLabel:marginLeft(5):width(MeasurementType.WRAP_CONTENT):height(iconHeight):setGravity(Gravity.CENTER)
    iconLabel:bgColor(updateLayout:bgColor())
    self.iconLabel = iconLabel
    updateLayout:addView(iconLabel)

    --添加显示
    self.baseLayout:addView(imageView):addView(imageViewLayout):addView(titleLabel):addView(updateLayout)
end


---@public
---@param count string
function _class:updateContentCountText(count)
    if not count then
        return
    end
    local text = StyleString(string.format("更新了%s篇内容", count))
    text:fontColor(_Color.Black):fontSize(10):fontStyle(FontStyle.BOLD)
    local textColor = _Color.MediumGray
    text:setFontColorForRange(textColor, 1, 3)
    text:setFontColorForRange(textColor, 4 + string.len(count), 3)
    self.iconLabel:styleText(text)
end

---@public
---@vararg string 图标urlString
function _class:updateContentIcons(...)
    local urls = { ... }
    local count = #urls
    if count > #self.iconViews then
        count = self.iconViews
    end

    if count == 0 then
        self.updateLayout:hidden(true)
    else
        self.updateLayout:hidden(false)
        for i = 1, count do
            local iconView = self.iconViews[i]
            iconView:image(urls[i])
        end
        local offset = (#self.iconViews - count) * 10
        self.iconLabel:marginLeft(-offset + 5)
    end
end


return _class