---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-09-05 12:05
---

local _class = {
    _classname = 'HTTPHandler',
    _version = '1.0',
    http = Http()
}

---@public
function _class:GET(url, param, complete)
    param = param or {}
    param["cachePolicy"] = CachePolicy.CACHE_THEN_API
    param["encType"] = EncType.NORMAL

    self.http:get(url, param, function(success, response, error)
        complete(success, response, error)
    end)
end

---@public
function _class:POST(url, param, complete)
    param = param or {}
    param["cachePolicy"] = CachePolicy.CACHE_THEN_API
    param["encType"] = EncType.NORMAL

    self.http:post(url, param, function(success, response, error)
        complete(success, response, error)
    end)
end

return _class