---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-09-05 12:05
---

local _class = {
    _name = "NavigationBar",
    _version = "1.0"
}

---@public
function _class:new()
    local o = {}
    setmetatable(o, {__index = self})
    return o
end

---@public
function _class:bar(title, fontSize)
    self.navibar = View():width(window:width()):height(_NaviBarHeight)

    self.titleLabel = Label()
    self.titleLabel:width(MeasurementType.WRAP_CONTENT):height(MeasurementType.WRAP_CONTENT):setGravity(Gravity.CENTER)
    self.titleLabel:text(title):textAlign(TextAlign.CENTER)

    self.titleLabel:setTextFontStyle(FontStyle.NORMAL)
    self.titleLabel:fontSize(fontSize or 16)

    self.navibar:addView(self.titleLabel)

    return self.navibar
end

return _class