---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by David.
--- DateTime: 2018/5/14 下午12:28
---
local _class = {}
_class._version = '1.0'
_class._classname = 'MomentNormalcell'

function MomentNormalcell()
    return _class
end

function _class:onCreate(cell, item)
    local width = cell.contentView:width()
    local height = cell.contentView:height()
    cell.bgImage = ImageView():marginTop(200 / 2 - 50):marginLeft(width / 2 - 50):width(100):height(100)
    --cell.bgImage:lazyLoad(false)
    cell.bgImage:contentMode(ContentMode.SCALE_TO_FILL)
    cell.contentView:setCornerRadiusWithDirection(8, MBit:bor(MBit:bor(RectCorner.TOP_LEFT, RectCorner.TOP_RIGHT), MBit:bor(RectCorner.BOTTOM_LEFT, RectCorner.BOTTOM_RIGHT)))

    cell.titleLabel = Label():width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT)
    cell.titleLabel:textColor(Color(0, 0, 0, 1))
    cell.titleLabel:fontSize(14)
    cell.contentView:bgColor(Color(255, 0, 0, 0.5))
    cell.titleLabel:height(30):x(20):y(50)
    --cell.titleLabel:setMatchParent(true)
    --cell.bgImage:setMatchParent(true)
    cell.contentView:addView(cell.bgImage):addView(cell.titleLabel)
    --cell.contentView:flexChildren({cell.bgImage, cell.titleLabel})

end

function _class:onLayout(cell, item)
    cell.bgImage:setImageUrl(item.iconName, 'lv_icon_3d')
    cell.titleLabel:text(item.title)
end

return _class
