---
--- Generated by Momo 
--- Created by bf.xiaotei.
--- DateTime: 2018/11/23
---

local _class = {}
_class._version = '1.0'
_class._classname = 'AlertDemo'

function _class:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self

    return o
end

function _class:onCreate(window)
    local label1 = Label()
    label1:text("常规取消确认提示")

    label1:frame(Rect(20, 100, 150, 33))

    label1:bgColor(Color(121, 121, 121, 1.0))

    window:addView(label1)

    label1:onClick(function()
        local alert = Alert()
        alert:title("我是标题")
        alert:message("我是消息啦！！")

        alert:setCancel("取消按钮", function()
            print("点击了取消按钮！")
        end)

        alert:setOk("ok按钮", function()
            print("点击啦OK按钮")
        end)

        alert:show()

    end)

    local label2 = Label()
    label2:text("竖排多按钮")

    label2:frame(Rect(20, 150, 150, 33))

    label2:bgColor(Color(121, 121, 121, 1.0))

    window:addView(label2)

    label2:onClick(function()
        local alert = Alert()
        alert:title("我是标题")
        alert:message("我是消息啦！！")

        local btns = Array()
        btns:add("按钮1")
        btns:add("按钮2")
        btns:add("按钮3")
        btns:add("按钮4")
        btns:add("按钮5")

        alert:setButtonList(btns, function(number)
            print("点击了按钮", btns:get(number))
        end)

        alert:show()

    end)

    local label3 = Label()
    label3:text("单个按钮文案和回调")

    label3:frame(Rect(20, 200, 150, 33))

    label3:bgColor(Color(121, 121, 121, 1.0))

    window:addView(label3)

    label3:onClick(function()
        local alert = Alert()
        alert:title("我是标题")
        alert:message("我是消息啦！！")

        alert:setSingleButton("就我啦", function()
            print("点击了就我啦按钮")
        end)

        alert:show()

    end)

end

return _class

