---
--- Generated by Momo 
--- Created by bf.xiaotei.
--- DateTime: 2018/11/23
---


local _class = {}
_class._version = '1.0'
_class._classname = 'ImageButtonDemo'

function _class:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self

    return o
end

function _class:onCreate(window)
    local width = window:width()
    local btn = ImageButton()
    btn:frame(Rect(18, 100, width - 36, 115))
    btn:contentMode(ContentMode.SCALE_ASPECT_FILL)
    btn:setImage("https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1159386606,974071300&fm=200&gp=0.jpg", "https://moji.wemomo.com/attach/pimg_5b5703e8c769c.png")
    btn:bgColor(Color(121, 14, 54, 1.0))
    btn:padding(5, 10, 15, 20)
    --TODO Android 必须加onCLick()监听，才有效
    btn:onClick(function()
        Toast("onClick \nTODO: Android 必须加onCLick()监听，才有效",1)
    end)

    window:addView(btn)
end
return _class