---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XiongFangyu.
--- DateTime: 2018/10/22 下午6:17
---

local leftTop = View()
leftTop:width(50):height(50):bgColor(Color(0,0,0,1)):marginLeft(10):marginTop(10)
window:addView(leftTop)

local leftBottom = View()
leftBottom:width(50):height(50):bgColor(Color(0,0,0,1)):setGravity(Gravity.BOTTOM):marginTop(10):marginRight(10)
window:addView(leftBottom)

local rightTop = View()
rightTop:width(50):height(50):bgColor(Color(0,0,0,1)):setGravity(Gravity.RIGHT):marginLeft(10):marginBottom(10)
window:addView(rightTop)

local rightBottom = View()
rightBottom:width(50):height(50):bgColor(Color(0,0,0,1)):setGravity(MBit:bor(Gravity.BOTTOM, Gravity.RIGHT)):marginRight(10):marginBottom(10)
window:addView(rightBottom)
