---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/8/30 下午3:09
---


datasouce = {
    headIconName = "http://img.momocdn.com/album/4F/CF/4FCFA0D2-95E8-3C09-3760-142E6916CA1B20170701_S.jpg",
    summary = "安全等级：高",
    sections = {
        {
            sectionTitle = "通过以下设置可以提高安全等级",
            items = {
                {
                    iconName = "http://seopic.699pic.com/photo/50035/0520.jpg_wh1200.jpg",
                    title = "密码修改——1——100",
                    subtitle = nil,
                    height = 100,
                },
                {
                    iconName = "http://seopic.699pic.com/photo/50027/8874.jpg_wh1200.jpg",
                    title = "手机绑定——2——300",
                    subtitle = "已绑定",
                    height = 300,
                },
                {
                    iconName = "http://seopic.699pic.com/photo/50042/3858.jpg_wh1200.jpg",
                    title = "证件信息——3——100",
                    subtitle = "未绑定",
                    height = 100,
                },
                {
                    iconName = "http://seopic.699pic.com/photo/50034/3685.jpg_wh1200.jpg",
                    title = "登录保护--4--100",
                    subtitle = "已开启",
                    height = 100,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "登录保护--4--100",
                    subtitle = "已开启",
                    height = 100,
                },
                {
                    iconName = "http://img.momocdn.com/feedvideo/B4/9A/B49AB85D-34C8-0063-9F05-B23678D41D6C20180425_L.webp",
                    title = "登录保护--4--100",
                    subtitle = "已开启",
                    height = 100,
                },
            }
        },

    }
}
size = 6
local viewPager = ViewPager()
viewPager:setPreRenderCount(1)
local adapter = ViewPagerAdapter()
adapter:getCount(function()
    return size;
end)

adapter:reuseId(function(position)
    return 'same'
end)

adapter:initCell(function(cell, position)
    print('init', position)
    local normalCell = require("cells.ViewPagerCell")
    normalCell:onCreate(cell, nil)
end)

adapter:fillCellData(function(cell, position)
    print('fill', position)
    local normalCell = require("cells.ViewPagerCell")
    local section = datasouce.sections[1]
    local items = section.items;
    local detailItem = items[position]
    normalCell:onLayout(cell, detailItem.iconName)
end)

viewPager:autoScroll(true)




viewPager:recurrence(true)






viewPager:frameInterval(2)
viewPager:showIndicator(true)
viewPager:endDragging(function(position)
    print("endDragging position:", position)
end)
viewPager:setPageClickListener(function(position)
    Toast("click position: "..tostring(position),1)
    print('click position: '.. position)
end)

viewPager:adapter(adapter)

window:addView(viewPager)

local array = Array()
array:add('附近动态')
array:add('附近的人')
array:add('附近直播')
array:add('item4')
array:add('item5')
array:add('item6')
tabLayout = TabSegmentView(Point(0, 0), array)





--tabLayout:relatedToViewPager(viewPager)






tabLayout:setTabSelectedListener(function(index)
    Toast("select f.."..index,1)
end)
--tabLayout:bgColor(Color():hex(0xffff00):alpha(1))
tabLayout:selectScale(1.6)
tabLayout:normalFontSize(15)
tabLayout:setTapBadgeNumAtIndex(30, 3)

viewPager:padding(50, 0, 0, 0)
window:addView(tabLayout)

local label4 = Label()
label4:y(50)
label4:width(100)
label4:height(100)
label4:fontSize(16)
label4:text("mapmapmapmapmap")
label4:bgColor(Color():hex(0xffff00):alpha(1))
label4:onClick(function()
    print('gggg currentIndex:', tabLayout:currentIndex());
    tabLayout:setCurrentIndexAnimated(2)
    tabLayout:setTapBadgeNumAtIndex(20, 4)
    tabLayout:setRedDotHiddenAtIndex(3)
end)
window:addView(label4)

local str = '{\"status\": 0,\"msg\": \"SUCCESS\",\"data\": [{\"id\": 1,\"name\": \"xiaohong\"}, {\"id\": 2,\"name\": \"xiaoming\"}]}'
local map = StringUtil.jsonToMap(str)
print("wwwww", map:get("msg"))
print("wwwww", map:get("data"))
print("wwwww", map:get("status"))
print("wwwww", map:get("id"))

local toJson = StringUtil.mapToJSON(map)
print("wwwww:toJson", toJson)

viewPager:cellWillAppear(function(cell, position)
    print("ggggg cellWillAppear:", cell, position)
end)

viewPager:cellDidDisappear(function(cell, position)
    print("ggggg cellDidDisappear:", cell, position)
end)
--
--local v = ImageView()
--v:openRipple(true)
--v:bgColor(Color(100, 200, 200, 1))
--v:cornerRadius(10)
--v:width(200)
--v:height(200)
----v:text("111111222")
--window:addView(v)

