---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-08-23-08-2019 20:01
---

IdeaMassMainView = require("MMLuaKitGallery.IdeaMassView")
ideaMassMainView = IdeaMassMainView:new()
window:addView(ideaMassMainView:rootView())
