---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/11/15 下午8:54
---
--- 导航栏 高度85
---

local NavigationView = {}

function NavigationView:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    return o
end

function NavigationView:createSubview(titles)
    self.contentView = View()
    self.contentView:bgColor(WHITE)

    self.backBtn = View()
    self.backBtn:width(40):height(40):setGravity(Gravity.CENTER_VERTICAL):marginLeft(5)
    self.backBtn:onClick(function()
        luaSafeClick()

        Navigator:closeSelf(AnimType.Default)
    end)

    self.backImageView = ImageView()
    self.backImageView:image("https://s.momocdn.com/w/u/others/2018/10/30/1540902583576-nav_back.png")
    self.backImageView:width(20):height(20):setGravity(Gravity.CENTER)
    self.backBtn:addView(self.backImageView)

    local frame = Rect(200, 0, kScreenWidth - 100, kNavBarHeight)
    local margin_left = (kScreenWidth - frame:width())/2 - 40

    self.segmentView = TabSegmentView(frame, titles)
    self.segmentView:selectScale(1.5)
    self.segmentView:normalFontSize(15)
    self.segmentView:width(frame:width()):height(frame:height()):marginLeft(margin_left):setGravity(Gravity.CENTER_VERTICAL)

     self.segmentView:setAlignment(TabSegmentAlignment.RIGHT)
     self.segmentView:setTapBadgeTitleAtIndex("123",2)

    self.segmentView:setTabSpacing(5,0)


    self.segmentView:setItemTabClickListener(function(position)

        Toast('  点击位置 = ' .. tostring(position), 2)

    end)

    self.segmentView:setTabSelectedListener(function(y)
        Toast('  滑动选中位置 = ' .. tostring(y), 2)

    end)

    self.linear = LinearLayout(LinearType.HORIZONTAL)
    self.linear:width(kScreenWidth):height(kNavBarHeight):setGravity(Gravity.CENTER_VERTICAL):marginTop(kStatusBarHeight/2)

    self.linear:addView(self.backBtn):addView(self.segmentView)

    self.contentView:addView(self.linear)

end

function NavigationView:bindViewPager(pager)
    self.segmentView:relatedToViewPager(pager)
end


return NavigationView


