---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-09-05 12:05
---

local _class = {
    _name = 'SearchBox',
    _version = '1.0'
}

---@public
function _class:new()
    local o = {}
    setmetatable(o, {__index = self})
    return o
end

---@public
---@return SearchBox self
function _class:setup(text)
    local label = Label():marginTop(0):width(window:width() - 40):height(36):setGravity(Gravity.CENTER_HORIZONTAL)
    label:onClick(function()
        Toast("网红咖啡馆", 1)
    end)

    if not text then
        text = "大家都在搜\"网红咖啡馆\""
    end
    label:text(text):fontSize(14):textAlign(TextAlign.CENTER):textColor(Color(50, 50, 50, 0.4))
    label:bgColor(Color(50,50,50,0.1))
    label:cornerRadius(label:height() / 2.0)
    return label
end

return _class