---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/11/15 下午8:54
---
--- collection view cell
---

local CollectionViewCell = {}


function CollectionViewCell:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    return o
end

function CollectionViewCell:createSubview(size)
    self.width = size:width()
    self.height = size:height()
    self.roomNameBaseHeight = math.min(math.floor(self.width / 180 * 50), 50)
    self.avatarWidth = math.floor(self.width / 180 * 93)

    -- 0.0 begin 根视图
    self.contentView = View()
    self.contentView:bgColor(WHITE)
    self.contentView:cornerRadius(8)
    self.contentView:width(self.width):height(self.height):setGravity(Gravity.CENTER)
    -- 0.0 end

    self.baseLinear = LinearLayout(LinearType.VERTICAL)
    self.baseLinear:width(self.width):height(self.height)

    -- 1.0 begin 头像部分
    local margin_top = (self.height - self.avatarWidth - 16) / 2 - 3
    self.avatarBgView = View()
    self.avatarBgView:bgColor(Color(0, 0, 0, 0.03))
    self.avatarBgView:width(self.avatarWidth + 16):height(self.avatarWidth + 16):setGravity(Gravity.CENTER_HORIZONTAL):marginTop(margin_top)
    self.avatarBgView:cornerRadius(self.avatarWidth/2 + 8)

    self.avatarView = ImageView()
    self.avatarView:bgColor(WHITE_245)
    self.avatarView:cornerRadius(self.avatarWidth/2)
    self.avatarView:width(self.avatarWidth):height(self.avatarWidth):setGravity(Gravity.CENTER)
    self.avatarBgView:addView(self.avatarView)

    -- 1.1 begin 标签
    local tag_height = math.max(math.ceil(18 * kScreenScale), 18)
    self.tagImageView = ImageView()
    self.tagImageView:bgColor(WHITE_245)
    self.tagImageView:width(42):height(tag_height):setGravity(MBit:bor(Gravity.BOTTOM, Gravity.CENTER_HORIZONTAL)):marginBottom(5)
    self.tagImageView:image("https://s.momocdn.com/w/u/others/2018/03/28/1522238318820-group8@2x.png")
    self.tagImageView:cornerRadius(tag_height / 2)
    self.avatarBgView:addView(self.tagImageView)

    self.tagLabel = Label()
    self.tagLabel:textAlign(TextAlign.CENTER)
    self.tagLabel:text("游戏中")
    self.tagLabel:fontNameSize("PingFangSC-Semibold", 10):textColor(DARK)
    self.tagLabel:width(42):height(tag_height):setGravity(MBit:bor(Gravity.BOTTOM, Gravity.CENTER_HORIZONTAL)):marginBottom(5)
    self.tagLabel:cornerRadius(tag_height / 2):bgColor(WHITE)
    self.avatarBgView:addView(self.tagLabel)
    -- 1.1 end

    self.baseLinear:addView(self.avatarBgView)
    -- 1.0 end

    -- 2.0 begin 昵称 & 性别
    self.userLinear = LinearLayout(LinearType.HORIZONTAL)
    self.userLinear:height(20):setWrapContent(true):setGravity(Gravity.CENTER_HORIZONTAL):marginTop(1)

    self.nickLabel = Label()
    self.nickLabel:fontNameSize("PingFangSC-Medium", 14):textColor(WHITE)
    self.nickLabel:breakMode(BreakMode.TAIL)
    self.nickLabel:height(20):setWrapContent(true):setMaxWidth(self.width - 50)  -- 高20， 宽自适应

    self.genderImageView = ImageView()
    self.genderImageView:width(13):height(13):setGravity(Gravity.CENTER_VERTICAL):marginLeft(3.5)
    self.userLinear:addView(self.nickLabel):addView(self.genderImageView)

    self.baseLinear:addView(self.userLinear)
    -- 2.0 end

    -- 3.0 begin 房间信息
    self.roomInfoLabel = Label()
    self.roomInfoLabel:textAlign(TextAlign.CENTER)
    self.roomInfoLabel:fontNameSize("PingFangSC-Regular", 12):textColor(Color(255, 255, 255, 0.8))
    self.roomInfoLabel:width(self.width):height(16.5):marginTop(1)

    self.baseLinear:addView(self.roomInfoLabel)
    -- 3.0 end

    -- 4.0 begin 房间名称
    local margin_top = self.avatarWidth - 3 + 9 + 20 + 16 + self.roomNameBaseHeight

    self.roomNameLabel = Label()
    self.roomNameLabel:textColor(DARK):lines(2):breakMode(BreakMode.TAIL):fontNameSize("PingFangSC-Semibold", 15)
    -- self.roomNameLabel:bgColor(WHITE):padding(14, 15, 14, 15)
    self.roomNameLabel:setWrapContent(true):setMaxWidth(self.width - 34):setMinWidth(self.roomNameBaseHeight):marginLeft(15):marginRight(15)
    self.roomNameLabel:setGravity(Gravity.CENTER_HORIZONTAL):marginTop(- margin_top)
    self.roomNameLabel:cornerRadius(8)

    self.triangleView = ImageView()
    self.triangleView:image("https://img.momocdn.com/banner/D5/60/D5607310-0B46-8513-2C7B-B92AE6D40B0D20180301.png")
    self.triangleView:width(12):height(5):setGravity(Gravity.CENTER_HORIZONTAL)

    self.baseLinear:addView(self.roomNameLabel):addView(self.triangleView)
    -- 4.0 end


    self.contentView:addView(self.baseLinear)
end

function CollectionViewCell:fillData(info)
    self.info = info

    local colorStr  = info:get("background_color")
    local desc      = info:get("desc")

    local topic = info:get("topic")
    local user  = info:get("user")

    self.avatarView:image(topic:get("icon"))
    self.roomInfoLabel:text(desc or "")
    self.nickLabel:text(user:get("name"))

    if user:get("sex") == "F" then
        self.genderImageView:image("https://s.momocdn.com/w/u/others/2018/10/24/1540350773889-female.png")
    else
        self.genderImageView:image("https://s.momocdn.com/w/u/others/2018/10/24/1540350538944-male.png")
    end

    self.contentView:bgColor(ColorWithRGBString(colorStr))
    local roomName = topic:get("text")
    if StringUtil:length(roomName) > 2 then
        self.roomNameLabel:textAlign(TextAlign.LEFT)
    else
        self.roomNameLabel:textAlign(TextAlign.CENTER)
    end
    self.roomNameLabel:text(roomName)

    local gameStatus = info:get("game_status")
    if gameStatus == 1 then
        self.tagLabel:hidden(true)
        self.tagImageView:hidden(false)
    elseif gameStatus == 2 then
        self.tagLabel:hidden(false)
        self.tagImageView:hidden(true)
        self.tagLabel:text("游戏中")
        self.tagLabel:textColor(DARK)
    elseif gameStatus == 3 then
        self.tagLabel:hidden(false)
        self.tagImageView:hidden(true)
        self.tagLabel:text("准备中")
        self.tagLabel:textColor(Color(0, 214, 228, 1))
    else
        self.tagLabel:hidden(true)
        self.tagImageView:hidden(true)
    end
end


function CollectionViewCell:calculateStyleString(str)
    if str and string.len(str) then
        return
    end

    local styleStr = StyleString(str)
    styleStr:fontSize(15)
    if IS_IOS then
        styleStr:fontName("PingFangSC-Semibold")
    end
    local size = styleStr:calculateSize(1000)

end

return CollectionViewCell