---
--- Generated by Momo 
--- Created by MOMO.
--- DateTime: 2018/11/21
---

local _class = {}
_class._version = '1.0'
_class._classname = 'System Demo'

function _class:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self

    return o
end

function _class:onCreate(contentView)

    local width = contentView:width()
    local height = contentView:height()

    local scrollView = ScrollView():height(height - 60):width(width):y(100)
    local Desc = Label():text("请用陌陌客户端扫码测试"):fontSize(19):setAutoFit(true):height(40):textAlign(TextAlign.CENTER):textColor(Color(0, 0, 0, 1)):x(10):y(50)
    contentView:addView(Desc)
    local showLabel = Label()--显示结果
    showLabel = demoUtils:initShowLabel(showLabel, width, height)
    showLabel:setAutoFit(true):y(0)
    scrollView:addView(showLabel)
    contentView:addView(scrollView)

    local showText = ""

    showText =  "OSVersion: " .. tostring(System:OSVersion())
    showText =  showText .."\n\n" .."AppVersion: " .. tostring(System:AppVersion())

    showText =  showText .."\n\n" .."SDKVersion: " .. tostring(System:SDKVersion())

    showText =  showText .."\n\n" .."SDKVersionInt: " .. tostring(System:SDKVersionInt())

    showText =  showText .."\n\n" .."iOS: " .. tostring(System:iOS())

    showText =  showText .."\n\n" .."Android: " .. tostring(System:Android())

    System:asyncDoInMain(function()
        showText = showText .. "\n\n" .."asyncDoInMain: " .. "do someThing"
        showLabel:text(showText)
    end)

    showText =  showText .."\n\n" .."scale: " .. tostring(System:scale())

    showText =  showText .."\n\n" .."screenSize: " .. tostring(System:screenSize())

    showText =  showText .."\n\n" .."navBarHeight: " .. tostring(System:navBarHeight())

    showText =  showText .."\n\n" .."stateBarHeight: " .. tostring(System:stateBarHeight())

    showText =  showText .."\n\n" .."homeIndicatorHeight: " .. tostring(System:homeIndicatorHeight())

    showText =  showText .."\n\n" .."tabBarHeight: " .. tostring(System:tabBarHeight())

    showText =  showText .."\n\n" .."deviceInfo: " .. tostring(System:deviceInfo())
    System:setTimeOut(function()
        showText =  showText .."\n\n" .. "setTimeOut: delay 1s, callbacked"
        showLabel:text(showText)
    end, 1)

    showLabel:text(showText)

    local btnInfo = { "showStatusBar", "hideStatusBar" }

    local tabsContainer = demoUtils:createCommonTabLinearLayout(contentView)
    local tabs = demoUtils:addTabFromData(btnInfo, tabsContainer)

    for i, v in pairs(tabs) do
        if i == btnInfo[1] then
            v:onClick(function()
               System:showStatusBar()
            end)
        elseif i == btnInfo[2] then
            v:onClick(function()
               System:hideStatusBar()
            end)
        end
    end
end

return _class