#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://git.wemomo.com/ios/Specs.git'
#source 'https://git.wemomo.com/alpha-ios/wemomo-alpha-podspecs.git'

platform :ios, '8.0'

target 'MLN_Example' do
  pod 'MLN', :path => '../../'
  pod 'MLNDevTool', :path => '../../'
  pod 'AFNetworking', '~> 3.0'
  pod 'MJRefresh', '3.1.16'
  pod 'SDCycleScrollView','>= 1.80'
  pod 'Toast', '~> 4.0.0'
end

target 'MLN_Tests' do
  inherit! :search_paths
  #
  pod 'MLN', :path => '../../'
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'

end
