---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhang.ke.
--- DateTime: 2018/12/20 下午6:16
---
local width = window:width();
local height = window:height();
local text = "keye"

local label = Label():lines(0):width(width - 120):height(MeasurementType.WRAP_CONTENT):fontSize(14):textColor(Color(255, 255, 255, 1))
local scrollView = ScrollView():marginLeft(120):width(width - 120):height(height):bgColor(Color(125, 123, 123, 1))
scrollView:addView(label)
window:addView(scrollView)

local audio = AudioPlayer()
local path = nil

audio:setDownloadCallback(function(table)
    local resultCode = table:get("resultCode");
    local msg = table:get("msg")
    path = table:get("path")
    if path then
        audio:play(path)
    end
    text = text .. "\n resultCode: " .. tostring(resultCode) .. ", path: " .. path
    label:text(text)
end)
audio:setProgressCallback(function(progress, total)
    print("progress: " .. tostring(progress) .. ", total: " .. tostring(total))
end)

audio:setPlayingCallback(function(status, msg)
    text = text .. "\n status: " .. status
    label:text(text)
end)

--audio:accuracy(1000)

local btn = Label():text("download"):width(100):height(100):bgColor(Color(125, 123, 123, 1)):textAlign(TextAlign.CENTER)
btn:onClick(function()
    audio:download("http://s.momocdn.com/w/u/others/2018/12/07/1544163948064-source.mp3", true)
end)
window:addView(btn)

local btn = Label():text("resume"):marginTop(120):width(100):height(100):bgColor(Color(125, 123, 123, 1)):textAlign(TextAlign.CENTER)
btn:onClick(function()
    audio:resume()
end)
window:addView(btn)

local btn = Label():text("pause"):marginTop(240):width(100):height(100):bgColor(Color(125, 123, 123, 1)):textAlign(TextAlign.CENTER)
btn:onClick(function()
    audio:pause()
end)
window:addView(btn)

local btn = Label():text("stop"):marginTop(360):width(100):height(100):bgColor(Color(125, 123, 123, 1)):textAlign(TextAlign.CENTER)
btn:onClick(function()
    audio:stop()
end)
window:addView(btn)
local count = 1
local btn = Label():text("isPlaying"):marginTop(480):width(100):height(100):bgColor(Color(125, 123, 123, 1)):textAlign(TextAlign.CENTER)
btn:onClick(function()
    count = count + 1
    audio:repeatCount(count)
    text = text .. "\n isPlaying: " .. tostring(audio:isPlaying()) .. ",count: " .. tostring(count)
    label:text(text)
end)
window:addView(btn)


