---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/12/19 下午2:59
---

local _class = {}
_class._version = '1.0'
_class._classname = ''

function _class:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self

    return o
end

function _class:onCreate(window)
    local width = window:width()
    local height = window:height()
    local mColor = Color()

    local colorView = View():height(100):width(width):bgColor(Color(255, 255, 0, 1))
    window:addView(colorView)

    local editAlpha = EditTextView():textColor(Color(0, 0, 0, 1)):y(120):x(10):height(60):width(60):bgColor(Color(123, 123, 123, 1))
    editAlpha:fontSize(23):placeholder("alpha")
    window:addView(editAlpha)

    local editR = EditTextView():textColor(Color(0, 0, 0, 1)):y(120):x(80):height(60):width(60):bgColor(Color(123, 123, 123, 1))
    editR:fontSize(16):placeholder("red")
    editR:inputMode(EditTextViewInputMode.Number)
    window:addView(editR)

    local editG = EditTextView():textColor(Color(0, 0, 0, 1)):y(120):x(150):height(60):width(60):bgColor(Color(123, 123, 123, 1))
    editG:fontSize(16):placeholder("green")
    editG:inputMode(EditTextViewInputMode.Number)
    window:addView(editG)

    local editB = EditTextView():textColor(Color(0, 0, 0, 1)):y(120):x(220):height(60):width(60):bgColor(Color(123, 123, 123, 1))
    editB:fontSize(16):placeholder("blue")
    editB:inputMode(EditTextViewInputMode.Number)
    window:addView(editB)

    local reloadBtn = Label():x(10):y(200):height(30):width(80):text("Color()"):bgColor(Color(255, 123, 123, 1))
    reloadBtn:onClick(function()
        colorView:bgColor(Color(tonumber(editR:text()), tonumber(editG:text()), tonumber(editB:text()), tonumber(editAlpha:text())))
    end)
    window:addView(reloadBtn)

    local reloadBtn = Label():x(100):y(200):height(30):width(80):text("hex(0x00ff00)"):bgColor(Color(255, 123, 123, 1))
    reloadBtn:onClick(function()
        mColor:hex(0x00ff00)
        colorView:bgColor(mColor)
    end)
    window:addView(reloadBtn)

    local reloadBtn = Label():x(190):y(200):height(30):width(80):text("hex(0xff00ff)"):bgColor(Color(255, 123, 123, 1))
    reloadBtn:onClick(function()
        mColor:hex(0xff00ff)
        colorView:bgColor(mColor)
    end)

    window:addView(reloadBtn)
    local reloadBtn = Label():x(280):y(200):height(30):width(80):text("alpha()"):bgColor(Color(255, 123, 123, 1))
    reloadBtn:onClick(function()

        mColor:alpha(tonumber(editAlpha:text()))
        colorView:bgColor(mColor)
    end)
    window:addView(reloadBtn)

end

return _class