---
--- Generated by Momo
--- Created by bf.xiaotei
--- DateTime: 2018/11/23
---
-- setCornerImage，setCornerImage  自动切割图片圆角，接口缺失

local _class = {}
_class._version = '1.0'
_class._classname = 'ImageViewDemo'

function _class:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self

    return o
end

function _class:onCreate(window)
    local screen_w = window:width()
    local screen_h = window:height()

    local scrollV = ScrollView()
    scrollV:frame(Rect(0, 0, screen_w, screen_h))
    scrollV:contentSize(Size(screen_w, screen_h * 2))

    window:addView(scrollV)

    local imgV1 = ImageView()
    local label1 = Label()
    label1:text("默认样式")
    label1:textColor(Color(124, 45, 10, 1.0))

    imgV1:frame(Rect(10, 100, 200, 120))
    label1:frame(Rect(220, 130, 100, 30))

    imgV1:image("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1545290220838&di=998913d9e7e0e427d744e33319223050&imgtype=0&src=http%3A%2F%2Fimg.czvv.com%2Fsell%2F4ef9be5fe5880130983dd75b%2F20170911161343368.jpg")

    imgV1:bgColor(Color(21, 122, 11, 1.0))

    imgV1:padding(5, 5, 5, 5)

    scrollV:addView(imgV1)
    scrollV:addView(label1)

    local imgV2 = ImageView()
    local label2 = Label()
    label2:text("SCALE_TO_FILL")
    label2:textColor(Color(124, 45, 10, 1.0))

    imgV2:frame(Rect(10, 230, 200, 120))
    label2:frame(Rect(220, 260, 200, 30))

    imgV2:contentMode(ContentMode.SCALE_TO_FILL)

    imgV2:image("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1545290220838&di=998913d9e7e0e427d744e33319223050&imgtype=0&src=http%3A%2F%2Fimg.czvv.com%2Fsell%2F4ef9be5fe5880130983dd75b%2F20170911161343368.jpg")

    imgV2:bgColor(Color(21, 122, 11, 1.0))

    imgV2:padding(5, 5, 5, 5)

    scrollV:addView(imgV2)
    scrollV:addView(label2)

    local imgV3 = ImageView()
    local label3 = Label()
    label3:text("SCALE_ASPECT_FIT")
    label3:textColor(Color(124, 45, 10, 1.0))

    imgV3:frame(Rect(10, 360, 200, 120))
    label3:frame(Rect(220, 370, 200, 30))

    imgV3:contentMode(ContentMode.SCALE_ASPECT_FIT)

    imgV3:image("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1545290220838&di=998913d9e7e0e427d744e33319223050&imgtype=0&src=http%3A%2F%2Fimg.czvv.com%2Fsell%2F4ef9be5fe5880130983dd75b%2F20170911161343368.jpg")

    imgV3:bgColor(Color(21, 122, 11, 1.0))

    imgV3:padding(5, 5, 5, 5)

    scrollV:addView(imgV3)
    scrollV:addView(label3)

    local imgV4 = ImageView()
    local label4 = Label()
    label4:text("SCALE_ASPECT_FILL")
    label4:textColor(Color(124, 45, 10, 1.0))

    imgV4:frame(Rect(10, 490, 200, 120))
    label4:frame(Rect(220, 500, 200, 30))

    imgV4:contentMode(ContentMode.SCALE_ASPECT_FILL)

    imgV4:image("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1545290220838&di=998913d9e7e0e427d744e33319223050&imgtype=0&src=http%3A%2F%2Fimg.czvv.com%2Fsell%2F4ef9be5fe5880130983dd75b%2F20170911161343368.jpg")

    imgV4:bgColor(Color(21, 122, 11, 1.0))

    imgV4:padding(5, 5, 5, 5)

    scrollV:addView(imgV4)
    scrollV:addView(label4)

    local imgV5 = ImageView()
    local label5 = Label()
    label5:text("CENTER")
    label5:textColor(Color(124, 45, 10, 1.0))

    imgV5:frame(Rect(10, 620, 200, 120))
    label5:frame(Rect(220, 630, 200, 30))

    imgV5:contentMode(ContentMode.CENTER)

    imgV5:image("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1545290220838&di=998913d9e7e0e427d744e33319223050&imgtype=0&src=http%3A%2F%2Fimg.czvv.com%2Fsell%2F4ef9be5fe5880130983dd75b%2F20170911161343368.jpg")

    imgV5:bgColor(Color(21, 122, 11, 1.0))

    imgV5:padding(5, 5, 5, 5)

    scrollV:addView(imgV5)
    scrollV:addView(label5)

    local imgV6 = ImageView()
    local label6 = Label()
    label6:text("startAnimationImages")
    label6:textColor(Color(124, 45, 10, 1.0))

    imgV6:frame(Rect(10, 760, 200, 120))
    label6:frame(Rect(220, 780, 200, 30))

    imgV6:contentMode(ContentMode.CENTER)

    local imgs = { "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1159386606,974071300&fm=200&gp=0.jpg",
                   "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1135295638,3697638664&fm=200&gp=0.jpg",
                   "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1640210176,316780632&fm=27&gp=0.jpg",
                   "https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=729382916,2146689896&fm=27&gp=0.jpg" }
    --两种类型 都支持
    --local imgs = Array()
    --imgs:add("https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1159386606,974071300&fm=200&gp=0.jpg")
    --imgs:add("https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1135295638,3697638664&fm=200&gp=0.jpg")
    --imgs:add("https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=1640210176,316780632&fm=27&gp=0.jpg")
    --imgs:add("https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=729382916,2146689896&fm=27&gp=0.jpg")

    imgV6:startAnimationImages(imgs, 5, true)

    imgV6:bgColor(Color(21, 122, 11, 1.0))

    imgV6:padding(5, 5, 5, 5)

    scrollV:addView(imgV6)
    scrollV:addView(label6)
end

return _class