---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XiongFangyu.
--- DateTime: 2019/3/28 5:03 PM
---

local lua_printer = {}
function print_r ( t )
    local print_r_cache={}
    local function sub_print_r(t,indent)
        if (print_r_cache[tostring(t)]) then
            print(indent.."*"..tostring(t))
        else
            print_r_cache[tostring(t)]=true
            if (type(t)=="table") then
                for pos,val in pairs(t) do
                    if (type(val)=="table") then
                        print(indent.."["..tostring(pos).."] => "..tostring(t).." {")
                        sub_print_r(val,indent..string.rep(" ",string.len(tostring(pos))+8))
                        print(indent..string.rep(" ",string.len(tostring(pos))+6).."}")
                    elseif (type(val)=="string") then
                        print(indent.."["..tostring(pos)..'] => "'..val..'"')
                    else
                        print(indent.."["..tostring(pos).."] => "..tostring(val))
                    end
                end
            else
                print(indent..tostring(t))
            end
        end
    end
    if (type(t)=="table") then
        print(tostring(t).." {")
        sub_print_r(t,"  ")
        print("}")
    else
        sub_print_r(t,"  ")
    end
    print()
end
lua_printer.print_r = print_r
return lua_printer